name: Run tests

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install build dependencies
        run: |
          python -m pip install build --user
      - name: Build package
        run: |
          python -m build
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          retention-days: 1
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Install wheel and test dependencies
        run: |
          python -m pip install --upgrade pip
          find ./dist/*.whl | xargs python -m pip install
          python -m pip install pytest
      - name: Run tests
        run: |
          python -m pytest
